version: '3'
services:
  import-order:
    build: .
    image: mofsesam/import-order:latest
    ports:
    - "5000:5000"
    environment:
      SUBDOMAIN: "test" 
      API_ROOT: "my.test/api/"
      DEBUG: True 
      LOG_LEVEL: "INFO"